site_name: ChalkBot - Documentation
nav:
  - Home:
    - 'index.md'
  - Hardware:
    - 'hardware/index.md'
  - Software:
    - 'software/index.md'
    - Canvas Simulation:
      - How to use the ChalkBot Simulator: 'software/simulation/simulator-usage.md'
      - How the simulator and canvas work: 'software/simulation/canvas-simulator.md'
    - Gyro Steuerung:
      - Gyro Control: 'software/gyro/gyro-control.md'
    - Raspberry Pi:
      - Rasoberry Pi Set Up: 'software/raspberry-pi/raspberry-pi.md'
      - Raspberry Pi Configuration: 'software/raspberry-pi/raspberry-pi-configuration.md'
      - Diet Pi: 'software/raspberry-pi/diet-pi.md'
      - Gamepad Input Script: 'software/raspberry-pi/gamepad-input-script.md'
      - Problems and Solutions: 'software/raspberry-pi/problems-solving.md'
    - PS2 Gamepad:
      - PS2 Controls - Software: 'PS2 Controls - Software.md'
      - PS2 Controls - Hardware: 'PS2 Controls - Hardware.md'
    
theme:
  name: material
  favicon: img/favicon.ico
  logo: img/favicon.ico
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  #- stella.tilde2
  #- stella.wikilinks

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/naoteamhumboldt
    - icon: fontawesome/brands/github
      link: https://github.com/BerlinUnited
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/teamhumboldt